  
#ifndef _COMMANDS_H
#define _COMMANDS_H

 const char new_line= '\n';

//ADC FETCH COMMANDS
#define FETCH_ADC0 "CROSS+ADC0"
#define FETCH_ADC1 "CROSS+ADC1"
#define FETCH_ADC2 "CROSS+ADC2"
#define FETCH_ADC3 "CROSS+ADC3"
#define FETCH_ADC4 "CROSS+ADC4"
#define FETCH_ADC5 "CROSS+ADC5"
#define FETCH_ADC6 "CROSS+ADC6"
#define FETCH_ADC7 "CROSS+ADC7"
#define FETCH_ADC8 "CROSS+ADC8"
#define FETCH_ADC9 "CROSS+ADC9"
#define FETCH_ADC10 "CROSS+ADC10"
#define FETCH_ADC11 "CROSS+ADC11"
#define FETCH_ADC12 "CROSS+ADC12"
#define FETCH_ADC13 "CROSS+ADC13"
#define FETCH_ADC14 "CROSS+ADC14"
#define FETCH_ADC15 "CROSS+ADC15"



#endif //_COMMANDS_H